### PR TITLE
Code review request for apple clone

### PR DESCRIPTION
**Pull request by Meltrust**
# Apple homepage clone.

In this project, I cloned an Apple homepage.  The objective was to practice backgrounds and gradients.

## Steps:

- Set up GitHub repo.
- Wrote HTML and CSS files using semantic code, flex, and grid display properties.  I also used linear gradients and CSS backgrounds.
- Added images and icons.
- Set up linter and corrected errors.
- Ran code through a validator, and corrected warnings. 
- Added descriptive Readme.
- I opened this pull request in order to get the code reviewed.

Thank you.

### CODE REVIEW

**Review by davidmrtz-dev — CHANGES_REQUESTED** [review]
## Hi @Meltrust  . 👨‍🚀  
### Very good job so far.
### However, the following issues need to be fixed before moving on  👨‍💻  ⬇️ 

****
- [x] Html Validator.
There's a couple of issues on the validator, the validator should throw 0 errors or warnings to ensure that the code is clean and follows best practices. 😄 

Screen Shot 2020-03-21 at 1 17 46 PM
****
- [x] Descriptive Pull Request.
The pull request description goes to the main point and it's ok but you can be more descriptive about the work you did on this project, for example:
- Descriptive Readme..
- Implemented stickler ci linters and configs.
- Followed good practices on CSS. (where and why?)
etc...
As described on pathwright:
Use meaningful names for your Pull Requests and add a short summary of its content as described [here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/).
Screen Shot 2020-03-21 at 1 31 27 PM
****
- [x] CSS issue.
There's an issue on the CSS file that breaks the CSS and is not displaying the styling correctly.
Check where it comes from and fix it to display the styling and images properly.

Screen Shot 2020-03-21 at 1 33 54 PM

****

### **Please kindly make the changes required and submit for re-review once you are ready!** 🙏 

****

### Status: Changes required. ♻️  👀 
****

Happy coding! 😄 💻  
If you have any questions or need help, you can message me on slack (@ David Eli Martinez Garcia).

**[TSE:  David Elí]** 👨‍💻 
Github: [@davitomix](https://github.com/davitomix)
Twitter: [@davitomix](https://twitter.com/davitomix007)
Linkedin: [David Elí Martínez García](https://www.linkedin.com/in/davideligarcia/)

**Comment by Meltrust** [comment]
Thank you @davitomix!  

I think I corrected everything.

**Review by MarioDena — APPROVED** [review]
Hello my name is Mario! Great work on your project!

You've implemented all the requested changes and to be honest you did a great work! 🎖 

## This project is approved! feel free to merge and good luck on your journey 😄 

## Code review by Mario Enrique Delgado Naranjo

**Comment by Meltrust** [comment]
Thank you!!!!!

**Pull request merged**
